import firebase from 'react-native-firebase';
import PushNotification from 'react-native-push-notification';
// Optional flow type
import  { RemoteMessage } from 'react-native-firebase';
import Sound from 'react-native-sound';
export default async (message: RemoteMessage) => {
    // handle your message
    var sound1 = new Sound('ring', '',
    (error, sound) => {
      if (error) {
        alert('error' + error.message);
        return;
      }
       sound1.play(() => {
         sound1.release();
       });
    });

    setTimeout(() => {
        sound1.stop();
   }, 4000);
    console.log("background calll notifcation  ");
    PushNotification.localNotification({
        /* Android Only Properties */
        id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        ticker: "My Notification Ticker", // (optional)
        autoCancel: true, // (optional) default: true
        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
        smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
        subText: "This is a subText", // (optional) default: none
        color: "red", // (optional) default: system default
        vibrate: false, // (optional) default: true
        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
        tag: 'some_tag', // (optional) add tag to message
        group: "group", // (optional) add group to message
        ongoing: false, // (optional) set whether this is an "ongoing" notification
        priority: "high", // (optional) set notification priority, default: high
        visibility: "private", // (optional) set notification visibility, default: private
        importance: "high", // (optional) set notification importance, default: high
        soundPath:"ring",
        //volume: 0.0,
        /* iOS only properties */
       
        /* iOS and Android properties */
        title: "My Notification Title", // (optional)
        message: "My Notification Message", // (required)
        playSound: false, 
        sound: false,// (optional) default: true
       soundName: 'ring', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
        number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
        repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
        actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
    });
    return Promise.resolve();
}